/*
 *
 * AdminPage constants
 *
 */

export const DEFAULT_ACTION = "app/AdminPage/DEFAULT_ACTION";
export const ADMIN_GET_REQUESTED_USERS_FETCH = "app/AdminPage/ADMIN_GET_REQUESTED_USERS_FETCH";
export const ADMIN_GET_REQUESTED_USERS_FETCH_SUCCESS = "app/AdminPage/ADMIN_GET_REQUESTED_USERS_FETCH_SUCCESS";
export const ADMIN_GET_REQUESTED_USERS_FETCH_FAIL = "app/AdminPage/ADMIN_GET_REQUESTED_USERS_FETCH_FAIL";
export const ADMIN_PAGE_HANDLE_REQUEST = "app/AdminPage/ADMIN_PAGE_HANDLE_REQUEST";
export const ADMIN_PAGE_HANDLE_TABS = "app/AdminPage/ADMIN_PAGE_HANDLE_TABS";




