/*
 * AppConstants
 * Each action has a corresponding type, which the reducer knows and picks up on.
 * To avoid weird typos between the reducer and the actions, we save them as
 * constants here. We prefix them with 'yourproject/YourComponent' so we avoid
 * reducers accidentally picking up actions they shouldn't.
 *
 * Follow this format:
 * export const YOUR_ACTION_CONSTANT = 'yourproject/YourContainer/YOUR_ACTION_CONSTANT';
 */
// export const TOGGLE_MAIN_DRAWER = "app/TOGGLE_MAIN_DRAWER";
export const OPEN_MAIN_DRAWER = "app/OPEN_MAIN_DRAWER";
export const CLOSE_MAIN_DRAWER = "app/CLOSE_MAIN_DRAWER";
export const CHANGE_PANEL = "app/CHANGE_PANEL";
export const PI_FILTER_DATA_FETCH = "app/PI_FILTER_DATA_FETCH";
export const PI_FILTER_DATA_FETCH_SUCCESS = "app/PI_FILTER_DATA_FETCH_SUCCESS";
export const PI_FILTER_DATA_FETCH_FAIL = "app/PI_FILTER_DATA_FETCH_FAIL";
export const PI_FILTER_SET = "app/PI_FILTER_SET";
export const ON_OPENING_PI_GLOBAL_SETTINGS = "app/ON_OPENING_PI_GLOBAL_SETTINGS";
export const ON_CLOSING_PI_GLOBAL_SETTINGS = "app/ON_CLOSING_PI_GLOBAL_SETTINGS";
export const ON_CHANGE_PI_RISK_CONTROL_PANEL_DATA = "app/ON_CHANGE_PI_RISK_CONTROL_PANEL_DATA";
export const ON_CHANGE_PI_SHELF_LIFE_RISK_CONTROL_PANEL_DATA = "app/ON_CHANGE_PI_SHELF_LIFE_RISK_CONTROL_PANEL_DATA";
export const PI_RISK_CONTROL_ON_CHANGE_DATA_LOADED_CHANGE_STATUS = "app/PI_RISK_CONTROL_ON_CHANGE_DATA_LOADED_CHANGE_STATUS";
export const PI_SHELF_LIFE_RISK_CONTROL_ON_CHANGE_DATA_LOADED_CHANGE_STATUS = "app/PI_SHELF_LIFE_RISK_CONTROL_ON_CHANGE_DATA_LOADED_CHANGE_STATUS";
export const RISK_CONTROL_PANEL_SAVE_RISKS = "app/RISK_CONTROL_PANEL_SAVE_RISKS";
export const RISK_CONTROL_PANEL_SAVE_RISKS_COMPLETED = "app/RISK_CONTROL_PANEL_SAVE_RISKS_COMPLETED";
export const SHOW_APP_ALERT = "app/SHOW_APP_ALERT";
export const HANDLE_EXPLAIN_MODULE = "app/HANDLE_EXPLAIN_MODULE";
export const SCMOS_BRAND_TECH_RISK_CLASSIFICATION_DATA_FETCH = "app/SCMOS_BRAND_TECH_RISK_CLASSIFICATION_DATA_FETCH";
export const SCMOS_BRAND_TECH_RISK_CLASSIFICATION_DATA_FETCH_SUCCESS = "app/SCMOS_BRAND_TECH_RISK_CLASSIFICATION_DATA_FETCH_SUCCESS";
export const SCMOS_BRAND_TECH_RISK_CLASSIFICATION_DATA_FETCH_FAIL = "app/SCMOS_BRAND_TECH_RISK_CLASSIFICATION_DATA_FETCH_FAIL";
export const RISK_CONTROL_PANEL_SAVE_SHELF_LIFE_RISKS = "app/RISK_CONTROL_PANEL_SAVE_SHELF_LIFE_RISKS";
export const RISK_CONTROL_PANEL_SAVE_SHELF_LIFE_RISKS_COMPLETED = "app/RISK_CONTROL_PANEL_SAVE_SHELF_LIFE_RISKS_COMPLETED";


// rtm filters
export const FILTER_DATA_FETCH = "app/RTM/PI_FILTER_DATA_FETCH";
export const FILTER_DATA_SUCCESS = "app/RTM/FILTER_DATA_SUCCESS";
export const FILTER_DATA_FAIL = "app/RTM/FILTER_DATA_FAIL";
export const SELECTED_FILTERS_APPLY = "app/RTM/SELECTED_FILTERS_APPLY";
export const RESET_DEEP_DIVE = "app/RTM/RESET_DEEP_DIVE";

//rtm store filter
export const STORE_FILTER_DATA_FETCH = "app/RTM/STORE_FILTER_DATA_FETCH";
export const STORE_FILTER_DATA_SUCCESS = "app/RTM/STORE_FILTER_DATA_SUCCESS";
export const STORE_FILTER_DATA_FAIL = "app/RTM/STORE_FILTER_DATA_FAIL";

//pin my page
export const PIN_MY_PAGE = "app/RTM/PIN_MY_PAGE";
export const CHANGE_DATA_LOAD_STATUS = "app/RTM/CHANGE_DATA_LOAD_STATUS";

// pin/unpin the views
export const PIN_MY_VIEW = "app/RTM/PIN_MY_VIEW";
export const PIN_MY_VIEW_CONFIRM = "app/RTM/PIN_MY_VIEW_CONFIRM";
export const UNPIN_MY_VIEW = "app/RTM/UNPIN_MY_VIEW";
export const PIN_MY_VIEW_CLOSE_DIALOG = "app/RTM/PIN_MY_VIEW_CLOSE_DIALOG";

//Data exception handling alert
export const DATA_EXCEPTION_ALERT = "app/RTM/DATA_EXCEPTION_ALERT";
