/*
 *
 * DistributorView constants
 *
 */

export const DEFAULT_ACTION = "app/DistributorView/DEFAULT_ACTION";

//TREND CHART click
export const DISTRIBUTOR_TREND_CHART_DATA_FETCH = 'app/DistributorView/DISTRIBUTOR_TREND_CHART_DATA_FETCH';
export const DISTRIBUTOR_TREND_CHART_DATA_FETCH_SUCCESS = 'app/DistributorView/DISTRIBUTOR_TREND_CHART_DATA_FETCH_SUCCESS';
export const DISTRIBUTOR_TREND_CHART_DATA_FETCH_FAIL = 'app/DistributorView/DISTRIBUTOR_TREND_CHART_DATA_FETCH_FAIL';
export const DISTRIBUTOR_TREND_CHART_ON_FILTER_CHANGE = 'app/DistributorView/DISTRIBUTOR_TREND_CHART_ON_FILTER_CHANGE';
export const DISTRIBUTOR_TREND_TABLE_DATA_FETCH = 'app/DistributorView/DISTRIBUTOR_TREND_TABLE_DATA_FETCH';
export const DISTRIBUTOR_TREND_TABLE_DATA_FETCH_SUCCESS = 'app/DistributorView/DISTRIBUTOR_TREND_TABLE_DATA_FETCH_SUCCESS';
export const DISTRIBUTOR_TREND_TABLE_DATA_FETCH_FAIL = 'app/DistributorView/DISTRIBUTOR_TREND_TABLE_DATA_FETCH_FAIL';







